name: kernel build
stop_on_error: true
ordering:
    - package_manager
package_manager:
    undo: false
    lambdas:
        map:
            item: install
            element: e
            as_type: int
            output: ${e}
    assume_yes: true
    sub_components:
        install:
            - sub_comp1
    install:
        - bison
        - build-essential
        - flex
        - libncurses5-dev
        - ncurses-dev
        - libelf-dev
        - libssl-dev
        - tar
        - util-linux
        - xz-utils
        - bc
        - dwarves
        - xmlto
        - kmod
        - bc
        - git
        - cpio
        - perl
        - file
git:
    user.name: Dandy Cheng
    user.email: cheng.dandy@gmail.com