name: kernel build
stop_on_error: true
user_modules:
    - Create dev directory:
        command: mkdir -p ~/dev
        stdout_var: mkdir_res
    - Pull repo:
        rules:
            - if: ${mkdir_res} == 'success'
              then:
                command: echo "success"

package_manager:
    lambdas:
        foreach:
            data: str.concat
            macro: aptitude_install
            result_var: res
    assume_yes: true
    sub_components:
        install:
            - sub_comp1
    install:
        - bison
        - build-essential
        - flex
        - libncurses5-dev
        - ncurses-dev
        - libelf-dev
        - libssl-dev
        - tar
        - util-linux
        - xz-utils
        - bc
        - dwarves
        - xmlto
        - kmod
        - bc
        - git
        - cpio
        - perl
        - file
git:
    user.name: Dandy Cheng
    user.email: cheng.dandy@gmail.com