include $(VPX_TESTS)/unit/ut_common.mk

TEST_BINARY := sanitizerTest
DEPENDENCIES := yaml-cpp

INCLUDE_PATHS := \
	$(VPX_HEADERS) \
	$(DEPS_PATH)/yaml-cpp/source/include \
	$(VPX_TESTS)/test-framework/mocks \
	$(VPX_TESTS)/test-framework/mocks/stdlib
	
OBJ_FILE_PATHS := \
	$(OBJ_PATH)/yaml-cpp/source \
	$(OBJ_PATH)/vulpix